version: '3.8'
services:
  koishi-dev:
    image: koishijs/koishi
    ports:
      - "5140:5140"  # koishi控制台
      - "8080:8080"  # 如果需要其他端口
    volumes:
      - ./:/app/external/xxapi
      - ./data:/app/data
    environment:
      - NODE_ENV=development
    command: >
      sh -c "
        cd /app/external/xxapi &&
        npm install &&
        npm run build &&
        cd /app &&
        koishi start
      "
